docToolchain/aoc-2022

day00/rust/mr-kaffee/Cargo.toml
day00/rust/mr-kaffee/README.adoc
day00/rust/mr-kaffee/aoc/Cargo.toml
day00/rust/mr-kaffee/aoc/src/lib.rs
day00/rust/mr-kaffee/input.txt
day00/rust/mr-kaffee/src/lib.rs
day00/rust/mr-kaffee/src/main.rs
day00/rust/mr-kaffee/template/Cargo.toml
day00/rust/mr-kaffee/template/src/lib.rs
day00/rust/mr-kaffee/template/src/main.rs

Added day00/rust/mr-kaffee

---

day00/kotlin/RJPlog/README.adoc
day00/kotlin/RJPlog/README.adoc.txt
day00/kotlin/RJPlog/day2200.kt
day00/kotlin/RJPlog/day2200_puzzle_input.txt

Day00 solution

---

day00/python/jamhocken/README.adoc
day00/python/jamhocken/solution.py

Added Readme and Hello, World in Python.

Day0 in Python

---

day01/rust/razziel89/.gitignore
day01/rust/razziel89/Cargo.toml
day01/rust/razziel89/README.adoc
day01/rust/razziel89/src/data.rs
day01/rust/razziel89/src/io.rs
day01/rust/razziel89/src/main.rs

This is my solution for day 1. I'm happy to be back :) .

Add solution for day 1

---

day00/rust/AlexisTM/README.adoc
day01/rust/AlexisTM/README.adoc
day02/rust/AlexisTM/README.adoc
day02/rust/AlexisTM/src/main.rs
profiles/AlexisTM.adoc

This is hopefully adding more information about my solutions in the developer page.

AlexisTM: Add documentation for each problem & add my profile

---

day00/rust/AlexisTM/README.adoc
day01/rust/AlexisTM/README.adoc
day02/rust/AlexisTM/README.adoc
day02/rust/AlexisTM/src/main.rs

Well, it is my first time with adoc 👯

AlexisTM - Fixing documentation.

---

day02/rust/mr-kaffee/Cargo.toml
day02/rust/mr-kaffee/README.adoc
day02/rust/mr-kaffee/src/lib.rs

Alternative solution for day 02

---

day04/rust/mr-kaffee/README.adoc
day04/rust/mr-kaffee/src/lib.rs

Much cleaner parsing using short-cut ? operator

---

day07/rust/mr-kaffee/src/lib.rs

Improved day07

---

day07/rust/razziel89/src/data.rs
day07/rust/razziel89/src/main.rs
day08/rust/razziel89/.gitignore
day08/rust/razziel89/Cargo.toml
day08/rust/razziel89/README.adoc
day08/rust/razziel89/src/data.rs
day08/rust/razziel89/src/io.rs
day08/rust/razziel89/src/main.rs

Thanks to the internet for suggestion to manage the directory traversal with a stack. I also created my first iterator in rust.

Solution for day 8 and prettification for day 7

---

day00/rust/mr-kaffee/aoc/src/template.rs
day09/rust/mr-kaffee/README.adoc
day09/rust/mr-kaffee/src/lib.rs

- simpler parsing
- better printing
- use printing in tests

Improve day09

---

day09/rust/mr-kaffee/README.adoc
day09/rust/mr-kaffee/src/lib.rs

Inline and clean-up update

---

day09/python/jamhocken/solution.py

Sorry I missed the fact that I was not in my fork. :-(

Create solution.py for python day 09

---

day11/rust/mr-kaffee/src/lib.rs

Avoid usage of intermediate queue in round

Simplify solution

---

day00/rust/mr-kaffee/aoc/src/letters.rs
day00/rust/mr-kaffee/aoc/src/lib.rs
day10/rust/mr-kaffee/README.adoc
day10/rust/mr-kaffee/src/lib.rs

day10 with 'OCR'

---

day11/kotlin/RJPlog/README.adoc
day11/kotlin/RJPlog/day2211_1_2.kt
day11/kotlin/RJPlog/day2211_puzzle_input.txt

Took a long time, but finally I made it :-)

Day11 solution

---

day12/kotlin/RJPlog/README.adoc
day12/kotlin/RJPlog/day2212_1_2.kt

the adoc tags were wrong, so the solution was not properly displayed

Day12 solution

---

day13/rust/mr-kaffee/Cargo.toml
day13/rust/mr-kaffee/README.adoc
day13/rust/mr-kaffee/src/lib.rs

day13 without heap

---

day13/rust/mr-kaffee/src/lib.rs

Fix documentation

---

day13/rust/mr-kaffee/src/lib.rs

Simpler no-heap day13

---

day15/rust/mr-kaffee/Cargo.toml
day15/rust/mr-kaffee/README.adoc
day15/rust/mr-kaffee/src/lib.rs
day16/rust/mr-kaffee/Cargo.toml
day16/rust/mr-kaffee/src/lib.rs

Improvements day15 & day16

---

day18/rust/mr-kaffee/Cargo.toml
day18/rust/mr-kaffee/README.adoc
day18/rust/mr-kaffee/src/lib.rs

Improve day18

---

day17/rust/mr-kaffee/examples/animate.rs
day17/rust/mr-kaffee/src/lib.rs

Animation for day17

---

day17/rust/mr-kaffee/README.adoc
day17/rust/mr-kaffee/examples/animate.rs
day17/rust/mr-kaffee/src/lib.rs

Document animation

---

day19/rust/mr-kaffee/README.adoc
day19/rust/mr-kaffee/src/lib.rs
day19/rust/mr-kaffee/src/main.rs

Working solution for day19

---

day23/rust/mr-kaffee/README.adoc
day23/rust/mr-kaffee/src/lib.rs

Better solution
